### ISSUE TITLE
t/01-basic.t failing in Windows

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#158]
In trying to set up the Github CI with a Windows runner, I get the following  error messages:

```
Use of uninitialized value $xmin in addition (+) at D:\a\Perl-PDF-Builder\Perl-PDF-Builder\blib\lib/PDF/Builder/Basic/PDF/File.pm line 1489.
Can't call method "realise" on an undefined value at D:\a\Perl-PDF-Builder\Perl-PDF-Builder\blib\lib/PDF/Builder.pm line 528.
```

which causes the test to die before reaching the last isa_ok()

My first thought was that

```
$pdf = PDF::Builder->open(File::Spec->catfile('t/resources/sample.pdf'));
```

should be

```
$pdf = PDF::Builder->open(File::Spec->catfile('t', 'resources', 'sample.pdf'));
```

but that doesn't seem to make any difference.

I don't have access to a Windows machine to debug this, and it runs fine on Linux.

**Comment by PhilterPaper** [comment]
Odd. This test runs fine on Windows. There's something nagging me that I've seen this before, and it was fixed some time ago. Looking at the File.pm code, it does appear that there _might_ be a path to get to this line (1489) without setting `$xmin` to a value, but then why wouldn't it fail consistently? Could you double-check the PDF::Builder version being used for this CI code? Meanwhile, I'll think about whether $xmin should be set to some default value, or the line using it skipped if it's undefined.

**Comment by carygravel** [comment]
This is failing with your current HEAD.

The `$xmin` message is just a warning. Perl is dying on the next message. But I did define a default value for `$xmin`, which hushed the first message, but didn't solve the problem itself.

**Comment by carygravel** [comment]
Note that the Github CI runner for Windows is Server 2019. The package versions are [here](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md).

**Comment by PhilterPaper** [comment]
I'm running Perl 5.26.1 here. I suppose there might be something changed in Perl between there and 5.32 that broke something. Do you know of any listings of changes and removed capabilities (e.g., deprecated features removed) that might cause problems? Even better if they provide some workarounds that will work on everything from 5.20 and up (going to 5.22 this summer, BTW).

Any suggestions on the best way to test a wide range of Perl versions on one Windows machine? Unfortunately, Perl will overwrite another version that was previously installed, and I don't have virtual machines or other partitioning. I need to check if it's all in \Strawberry, or if stuff is dropped elsewhere (\Program Files, etc.). If there's a foolproof way to switch between Perl versions on testing, so I don't have to do complete reinstalls each time, that would be good. By the way, Strawberry Perl will also install a large library of CPAN packages, some of which don't like running at wrong Perl levels, so that library needs to be updated/swapped between for each version, too. If that's three Perl levels I install (5.20 or 5.22, 5.26, and 5.32), that means daily updates of all three package libraries (rather than one), which I'm not looking forward to!

I wonder if it's practical to rename \Strawberry to \Strawberry-5.26, install (and rename) \Strawberry-5.20 and \Strawberry-5.32, and use a batch file to rename the desired active version to \Strawberry? Each would have its own CPAN package library that would have to be kept updated, and I would of course have to manually update PDF::Builder in each (maybe that could be automated to copy the entire PDF::Builder subtree out of one and into the others). Any better ideas?

**Comment by carygravel** [comment]
[This guy](https://www.perlmonks.org/bare/?node_id=928888) has multiple versions installed and uses a batch script to switch between them.

There is also the [berrybrew](https://github.com/dnmfarrell/berrybrew) project.

You could also use docker images.

If you can get the berrybrew stuff working, I'd be tempted to work it into the Github CI.

Talking about the CI, once you have merged #156, I've lined up a couple of patches to run all the tests in the CI with and without Graphics::TIFF, ghostscript, and imagemagick. If you can find the cause of #158, then we can then add Windows to the CI as well.

**Comment by PhilterPaper** [comment]
Hmm. I like the idea of the first one. I had never heard of a "junction" (directory symbolic link) but that sounds like it might be easier than renaming the top-level directory from \strawberry-5.32 to \strawberry (and back). I'll have to take a deeper look at that soon. It sounds like I will not have to fool with PATH and will be able to use \strawberry as usual on the command line and in utilities. The only thing I'm not looking forward to is keeping all the CPAN packages that Strawberry installs up to date on a regular basis, but maybe I can automate it a bit better than I do now (keep a list of problem packages to exclude from updates so that the "upgrade" utility can run unattended daily).

The first order of business will be to install 5.32 and see why t/01-basic.t is failing.

**Comment by carygravel** [comment]
It looks as though you can [install berrybrew with choco](https://community.chocolatey.org/packages/berrybrew) and then use berrybrew to install Perl.

Therefore, It ought to be possible to have multiple Windows runners in the Github CI, each testing with a different version of Perl.

**Comment by PhilterPaper** [comment]
Good news. Once I took out the grouping of tests (now skip only 1 test at a time), 5.22 and 5.32 started working correctly. All t-tests now pass, including all the TIFF tests.

Note that Graphics::TIFF is still not installable on Perl 5.22.

**Comment by PhilterPaper** [comment]
Just a comment on the first item. I could not get t/tiff.t tests to work (appeared to be running tests they shouldn't have) _until_ I gave each test its own "skip" test and skipped just **1** test, not 2 or 4. Maybe this is a specific problem with Strawberry Perl and its CPAN-compatible utilities, but it looks like we'll have to stay with one test skipped at a time, unless someone can find a way around this. It's not a great burden, and I think it makes the code clearer anyway to just skip one test, as well as making it easier to insert or delete tests without having to remember to update the skip count.

Regarding the File::Spec->catfile usage, is this going to be needed on _all_ t-tests involving files? If so, why hasn't that shown up before? Keep in mind that function calls in Windows will accept / directory separators (also \ which is required for DOS command-line) and as long as we're doing relative paths, that should be adequate and OS-independent.

**Comment by carygravel** [comment]
> Regarding the File::Spec->catfile usage, is this going to be needed on _all_ t-tests involving files? If so, why hasn't that shown up before? Keep in mind that function calls in Windows will accept / directory separators (also \ which is required for DOS command-line) and as long as we're doing relative paths, that should be adequate and OS-independent.

Is this true of all Windows implementations of Perl, or only Strawberry Perl?

**Comment by PhilterPaper** [comment]
No, it runs fine on all Perl versions (5.22, 5.26, 5.32). All I can think of is that you have some problem in your Windows or Perl setup.

Regarding your question about having to skip only one test at a time, I can only try this on Strawberry Perl. I have no idea whether it fails on other Windows Perl installations, such as ActiveState. Since Strawberry seems to be the 800 pound gorilla in Perl on Windows, I'm content just to test on it.

**Comment by carygravel** [comment]
Not my Window/Perl setup - this is the Github CI, which is using Windows Server 2019 in a Docker container.

**Comment by PhilterPaper** [comment]
So if I update the test .yml stuff with your latest changes, to run Windows tests, you think I should see the same problem? Then at least I can try figuring out what it is. If I can't find it, does GitHub have any procedures for reporting problems and working with them to fix it?

**Comment by carygravel** [comment]
No. My CI2 changes in #162 are to get the full set of tests working in Linux and test various combinations of Graphics::TIFF and Ghostscript.

To reproduce this problem, add the following to `test.yml`

```
  full-windows:
    name: Full_Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install imagemagick dejavufonts
      - run: vcpkg install tiff:x86-windows ImageMagick:x64-windows-static
      - run: cpan Font::TTF GD IO::Compress Test::Exception Test::Memory::Cycle
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
```

Obviously, you'll have to commit and push, so I would do it in a new branch, as imagine you'll end up with lots of debugging commits.

**Comment by PhilterPaper** [comment]
I _think_ I created a branch "CI" and switched to it, then pushed a revised test.yml (per your previous instructions). It gave the following error on the CI run:
```
Run vcpkg install tiff:x86-windows ImageMagick:x64-windows-static
Computing installation plan...
Error: while loading imagemagick:
The port directory (C:\vcpkg\ports\imagemagick) does not exist
Error: failed to load port from C:\vcpkg\ports\imagemagick
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
Error: Process completed with exit code 1.
```
Is it thinking that C:\vcpkg\ is on _my_ machine or on GitHub? Are you running your modified test.yml on github.com or on a local repository? I would assume that if it's on github.com, that it would have the same packages available...

I haven't done any branches yet in GH, nor reset/revert of commits. I'm new at this. Are there any "cookbooks" or "cheat sheets" for doing basic operations? I found a couple sites: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging and https://opensource.com/article/18/6/git-reset-revert-rebase-commands and tried to follow these, but I'm not sure I did them right. Is a new branch visible to you on github.com/PhilterPaper/Perl-PDF-Builder, with a revised test.yml?

If I update the master branch with this test.yml code, can I assume that I'll see the same failure?

**Comment by carygravel** [comment]
I can see your branch and the failure [here](https://github.com/PhilterPaper/Perl-PDF-Builder/runs/2453432088?check_suite_focus=true). The mistake is mine. Please try this really basic recipe, which still shows the problem:

```
  basic-windows:
    name: Basic Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cpan Font::TTF GD IO::Compress Test::Exception Test::Memory::Cycle
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
```

You can see the results in [my branch](https://github.com/carygravel/Perl-PDF-Builder/runs/2455944332?check_suite_focus=true#step:5:248)

> Is it thinking that C:\vcpkg\ is on my machine or on GitHub? Are you running your modified test.yml on github.com or on a local > repository? I would assume that if it's on github.com, that it would have the same packages available...

None of this is local. This all runs in a docker container in the cloud organised by Github.

> I haven't done any branches yet in GH, nor reset/revert of commits. I'm new at this. Are there any "cookbooks" or "cheat sheets" > for doing basic operations? I found a couple sites: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging > and https://opensource.com/article/18/6/git-reset-revert-rebase-commands and tried to follow these, but I'm not sure I did them > right. Is a new branch visible to you on github.com/PhilterPaper/Perl-PDF-Builder, with a revised test.yml?
> 
> If I update the master branch with this test.yml code, can I assume that I'll see the same failure?

You seem to have done everything correctly. It is a good habit to get into to work in branches on new features or bugs until things work as they should. You can then update the master branch with the new commits, either by cherry-picking them, or by rebasing:

```
git checkout master
git rebase the_name_of_my_new_branch
```

**Comment by PhilterPaper** [comment]
OK, I seem to have reproduced your original problem. Besides 01-basic, there are 4 other t-tests (02-xrefstm, 03-xrefstm-index, circular-referenes, and rt120450) with the same failure. Maybe that will give me a clue.

It may just be a matter of additional setup needed for CI tests on Windows, but font-synfont and font-ttf both skip tests due to no DejaVu Sans, and font-type1 skips due to no URW Gothic L Book). tiff skips many tests due to 'no convert' (IM). I don't know if it's really missing GT (likely is).

Time to get to work on figuring out this thing!

**Comment by carygravel** [comment]
> It may just be a matter of additional setup needed for CI tests on Windows, but font-synfont and font-ttf both skip tests due to no DejaVu Sans, and font-type1 skips due to no URW Gothic L Book). tiff skips many tests due to 'no convert' (IM). I don't know if it's really missing GT (likely is).

IM and GT really are missing in this case, but that is OK. I suggest that after you fix this, we _add_ more tests to cover those combinations.

**Comment by PhilterPaper** [comment]
Assuming you're talking about the missing fonts, maybe I can change the t-tests to use a different TTF font (than DejaVu Sans) that is common to both Linux and Windows. I don't think any Type 1 (PS) fonts ship with Windows, so that may be a permanent problem (skip).

I presume that the tiff.t issues need to be dealt with by installing IM and GT for the test. GT can be dealt with by fixing the "optional" prereq problem (see #160) to install GT come hell or high water, but IM may be more of a problem on Windows.

**Comment by carygravel** [comment]
> Assuming you're talking about the missing fonts, maybe I can change the t-tests to use a different TTF font (than DejaVu Sans) that is common to both Linux and Windows. I don't think any Type 1 (PS) fonts ship with Windows, so that may be a permanent problem (skip).

I've found a DejaVu package for Windows, so that should be no problem.

> I presume that the tiff.t issues need to be dealt with by installing IM and GT for the test. GT can be dealt with by fixing the "optional" prereq problem (see #160) to install GT come hell or high water, but IM may be more of a problem on Windows.

This isn't an issue. There should be a set of test for each package combination, if only to make sure that the skips are working properly. So it is a good idea to also test this basic setup with minimum dependencies.

The thorniest problem will be getting Graphics::TIFF to install in the runner, because it needs libtiff where it can find it, and I don't know where vcpkg puts it. Once you have solved #158, I will attempt your suggestion of using Alien. This would also make things independent of the version that vcpkg ships, which isn't very new.

**Comment by PhilterPaper** [comment]
I've made some progress on this thing. File->open() is trying to read the xref table. It goes to the end of the file and searches backwards in 16-byte chunks until it finds 'startxref', and successfully picks up the offset amount on the next line (for t/resources/sample.pdf, it's 3837), Then it seeks to offset 3837, which is supposed to be 'xref', but is actually about 11 bytes _earlier_ in the file ('am endobjCRLFxref'). It therefore gets misaligned trying to read the xref table. By strange coincidence, there are 11 records ahead of the point it seeks to -- it looks like perhaps the file has 2 bytes (CRLF) at the end of each record, rather than the one byte (NL) the startxref offset value was apparently assuming! 

Now, why would this CI installation handle files differently than everyone else seems to be doing? CPAN installation, Windows, Linux all seem to behave the same way when running this code. It's just the CI that's acting strangely.

**Comment by carygravel** [comment]
> Now, why would this CI installation handle files differently than everyone else seems to be doing? CPAN installation, Windows, Linux all seem to behave the same way when running this code. It's just the CI that's acting strangely.

The CI runner _is_ in this case Windows - Windows Server 2019. Note that [git can be configured to play with line endings](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings) when committing and checking out - this is to present a file in the same way on both platforms. Perhaps this is the problem.

**Comment by carygravel** [comment]
Indeed adding a `.gitattributes` with

```
*.pdf     binary
```

was [enough to solve the problem](https://github.com/carygravel/Perl-PDF-Builder/runs/2464567397?check_suite_focus=true)!

The only thing to check is that it doesn't mess up anything locally for you in the PDFs you have committed to git.

**Comment by carygravel** [comment]
Indeed adding a `.gitattributes` with

```
*.pdf     binary
```

was [enough to solve the problem](https://github.com/carygravel/Perl-PDF-Builder/runs/2464567397?check_suite_focus=true)!

The only thing to check is that it doesn't mess up anything locally for you in the PDFs you have committed to git.

**Comment by PhilterPaper** [comment]
Awright! It did the job. Good work with the fix! The master branch is now running with basic-Windows CI. I'm sure you'll want to do more with it, and at some point close this ticket. If you want to continue Windows CI on this ticket for a while, that's OK by me.

I didn't make any changes or re-commits of PDF files. Is there anything I should be looking for? If I commit another PDF (or replace one) some time in the future, are you saying that its behavior may change?

**Comment by carygravel** [comment]
> Awright! It did the job. Good work with the fix! The master branch is now running with basic-Windows CI. I'm sure you'll want to do more with it, and at some point close this ticket. If you want to continue Windows CI on this ticket for a while, that's OK by me.

Your work leading to your comment about the line ending gave me the hint. It wouldn't have occurred to me otherwise. We've solved the basic problem. Let's close the ticket. I'll add to the Windows tests with PRs as soon as I have libtiff building with Alien.

> I didn't make any changes or re-commits of PDF files. Is there anything I should be looking for? If I commit another PDF (or replace one) some time in the future, are you saying that its behavior may change?

If everything looks fine to you, then no problem. The `.gitattributes` file should mean that any futures PDFs won't be touched.

Can you merge #162, then please? Then I'll get to work fixing #154.
